In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [6]:
# execution performance 
import numpy as np
import time
size = 10_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"time take by python list {end-start} seconds ")

np_arr = np.array(py_list)
start = time.time()
sq_list = np_arr**2
end = time.time()
print(f"time take by numpy array {end-start} seconds ")


time take by python list 7.585390329360962 seconds 
time take by numpy array 0.22973871231079102 seconds 


In [8]:
# memory performance
import sys
print(f"memory occupied by python list {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"memory occupied by numpy array {np_arr.nbytes} bytes")

memory occupied by python list 800000560000000 bytes
memory occupied by numpy array 80000000 bytes


In [13]:
# creation of numpy arrays
arr1 = np.array([1,2,3,4,5])
print(arr1, type(arr1), arr1.shape, arr1.dtype)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, type(arr2D), arr2D.shape, arr2D.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3) int64


In [31]:
# numpy from scratch
arr1 = np.zeros((2,3) , dtype="int64")
print(arr1)

arr2 = np.ones((5,))
print(arr2)

arr3 = np.full((2,3), 100)
print(arr3)

arr4 = np.arange(1,11)
print(arr4)

arr5 = np.eye(3,3)
print(arr5)

arr6 = np.linspace(1,100,5, dtype="int64") #evenly spaced array
print(arr6)


[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[100 100 100]
 [100 100 100]]
[ 1  2  3  4  5  6  7  8  9 10]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  1  25  50  75 100]


In [41]:
# Properties on array
arr = np.array([1,2,3,4,5])
print(np.size(arr))
print(arr.size)


arr2 = np.array([[0,9,8],[7,6,5],[4,3,2]])
print(np.ndim(arr2)) #show which type or dimension array this is 
print(arr.ndim)

print(arr.dtype) #show data type

print(arr2.shape) #dimensions row*col

# type casting
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3.astype(np.float64))

5
5
2
1
int64
(3, 3)
[[1. 2. 3.]
 [4. 5. 6.]]


In [42]:
# reshaping the array
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr, reshaped_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [11]:
# indexing in numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0], arr[4])

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0][1])

# fancy indexing
idx = [1,2,4]
print(arr[idx])

# boolean indexing
print(arr[arr % 2 == 0])

1 5
2
[2 3 5]
[2 4]


In [13]:
# slicing
arr = np.array([1,2,3,4,5,6])
print(arr[2:5])

[3 4 5]


In [16]:
# copy vs view
# python copy when do slicing while numpy does not
py_list = [100, 200, 300, 400, 500]
sub_list = py_list[0:3]
print(sub_list)
sub_list[0] = 1200
print(sub_list)
print(py_list)

arr = np.array([100, 200, 300, 400, 500])
sub_arr = arr[0:3]
print(sub_arr)
sub_arr[0] = 1200
print(sub_arr)
print(arr)

[100, 200, 300]
[1200, 200, 300]
[100, 200, 300, 400, 500]
[100 200 300]
[1200  200  300]
[1200  200  300  400  500]


In [5]:
# multidimentional array
import numpy as np
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))

# coloum wise sum
sum_of_columns = np.sum(arr2D, axis=0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [14]:
# 3d arrays
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D)

print(arr3D[:, 0 , :]) 

print(arr3D[0, 1, :])

arr3D[:, 0 , :] = 99
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[1 2]
 [7 8]]
[3 4]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [15]:
# vectorization
arr1 = np.array([6,5,2,6,8])
arr2 = np.array([3,5,6,7,10])
print(arr1+arr2)
print(arr1 ** 2)
print(arr2 + 3)

[ 9 10  8 13 18]
[36 25  4 36 64]
[ 6  8  9 10 13]


In [17]:
# broadcasting
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])          # shape (3, 2)

B = np.array([
    [10, 20]
])          # shape (1, 2)

res = A+B
print(res)

[[11 22]
 [13 24]
 [15 26]]


In [18]:
# normalization
arr = np.array([[1, 2],[3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [21]:
# calculations
# aggregation
arr = np.array([1,2,15,4,5])
print(np.sum(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.min(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))

27
5.4
25.04
1
4.0
0
2


In [27]:
# power functions
arr = np.array([1,2,15,4,5])
print(np.square(arr))
print(np.sqrt(arr).astype(int))
print(np.pow(arr, 3))

[  1   4 225  16  25]
[1 1 3 2 2]
[   1    8 3375   64  125]


In [31]:
# log values
arr = np.array([1,2,15,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 2.7080502  1.38629436 1.60943791]
[0.         0.30103    1.17609126 0.60205999 0.69897   ]
[0.         1.         3.9068906  2.         2.32192809]
[2.71828183e+00 7.38905610e+00 3.26901737e+06 5.45981500e+01
 1.48413159e+02]


In [38]:
# rounding
print(np.round(3.14))
print(np.round(3.98))
print(np.floor(3.14))
print(np.ceil(3.14))
arr = np.array([-1,-2,15,-4,5,4,2,8,9,15])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))


3.0
4.0
3.0
4.0
[-4 -2 -1  2  4  5  8  9 15]
[-4 -2 -1  2  4  5  8  9 15 15]
[ 1  2 15  4  5  4  2  8  9 15]
